=== docops-info/docops-extension-sever/src/main/resources/static/schemas/scorecard-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "DocOps Scorecard Generator Schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "initiativeTitle": {
      "type": "string"
    },
    "outcomeTitle": {
      "type": "string"
    },
    "initiativeItems": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "displayText": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "displayText"
        ]
      }
    },
    "outcomeItems": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "displayText": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "displayText"
        ]
      }
    },
    "scale": {
      "type": "number"
    },
    "scoreCardTheme": {
      "type": "object",
      "properties": {
        "titleColor": {
          "type": "string"
        },
        "initiativeTitleColor": {
          "type": "string"
        },
        "outcomeTitleColor": {
          "type": "string"
        },
        "backgroundColor": {
          "type": "string"
        },
        "initiativeBackgroundColor": {
          "type": "string"
        },
        "outcomeBackgroundColor": {
          "type": "string"
        },
        "initiativeDisplayTextColor": {
          "type": "string"
        },
        "outcomeDisplayTextColor": {
          "type": "string"
        },
        "arrowColor": {
          "type": "string"
        }
      },
      "required": [
        "titleColor",
        "initiativeTitleColor",
        "outcomeTitleColor",
        "backgroundColor",
        "initiativeBackgroundColor",
        "outcomeBackgroundColor",
        "initiativeDisplayTextColor",
        "outcomeDisplayTextColor",
        "arrowColor"
      ]
    },
    "slideShow": {
      "type": "boolean"
    }
  },
  "required": [
    "title",
    "initiativeTitle",
    "outcomeTitle",
    "initiativeItems",
    "outcomeItems",
    "scale"
  ]
}

=== docops-info/docops-extension-sever/src/main/resources/samples/score-yellow.json
{
  "title": "Initiative",
  "initiativeTitle": "Journey Starts",
  "outcomeTitle": "Outcomes Since",
  "initiativeItems": [
    {
      "displayText": "API Versioning",
      "description": "Host API versioning"
    },
    {
      "displayText": "Network Switch",
      "description": "Migrate IBM Websphere to Liberty Server with RHEL 8 and JSESSION ID fix with Application cache busting and versioning"
    },
    {
      "displayText": "MFA",
      "description": "Enabling single signon from server sign-in page"
    },
    {
      "displayText": "Product Elimination - from system"
    }
  ],
  "outcomeItems": [
    {
      "displayText": "API Versioning changes with backwards compatibility"
    },
    {
      "displayText": "Network Mark-In/Mark-Out Servers"
    },
    {
      "displayText": "Phased Rollout, Milestones and Release Candidate"
    },

    {
      "displayText": "Software toggle to Enable/Disable OAuth Server"
    }
  ],
  "scale": 1.0,
  "scoreCardTheme": {
    "titleColor": "#111111",
    "initiativeTitleColor": "#111111",
    "outcomeTitleColor":"#111111",
    "backgroundColor": "#230338",
    "initiativeBackgroundColor": "#FFAC41",
    "outcomeBackgroundColor": "#FFAC41",
    "initiativeDisplayTextColor": "#000000",
    "outcomeDisplayTextColor":"#000000",
    "arrowColor": "#F9D276"
  }
}

=== docops-info/docops-extension-sever/src/main/resources/samples/score2.json
{
  "title": "Initiative",
  "initiativeTitle": "Journey Begins with",
  "outcomeTitle": "Outcomes Since",
  "initiativeItems": [
    {
      "displayText": "API Versioning",
      "description": "Host API versioning"
    },
    {
      "displayText": "Network Switch",
      "description": "Migrate IBM Websphere to Liberty Server with RHEL 8 and JSESSION ID fix with Application cache busting and versioning"
    },
    {
      "displayText": "MFA",
      "description": "Enabling single signon from server sign-in page"
    },
    {
      "displayText": "Product Elimination - from system"
    }
  ],
  "outcomeItems": [
    {
      "displayText": "API Versioning changes with backwards compatibility"
    },
    {
      "displayText": "Network Mark-In/Mark-Out Servers"
    },
    {
      "displayText": "Phased Rollout, Milestones and Release Candidate"
    },

    {
      "displayText": "Software toggle to Enable/Disable OAuth Server"
    }
  ],
  "scale": 1.0,
  "scoreCardTheme": {
    "titleColor": "#9394a5",
    "initiativeTitleColor": "#9394a5",
    "outcomeTitleColor":"#9394a5",
    "backgroundColor": "#e4e5f1",
    "initiativeBackgroundColor": "#EBE3D5",
    "outcomeBackgroundColor": "#EBE3D5",
    "initiativeDisplayTextColor": "#111111",
    "outcomeDisplayTextColor":"#111111",
    "arrowColor": "#9394a5"
  }
}

=== docops-info/docops-extension-sever/src/main/resources/samples/score-pink.json
{
  "title": "Initiative",
  "initiativeTitle": "Journey Starts",
  "outcomeTitle": "Outcomes Since",
  "initiativeItems": [
    {
      "displayText": "API Versioning",
      "description": "Host API versioning"
    },
    {
      "displayText": "Network Switch",
      "description": "Migrate IBM Websphere to Liberty Server with RHEL 8 and JSESSION ID fix with Application cache busting and versioning"
    },
    {
      "displayText": "MFA",
      "description": "Enabling single signon from server sign-in page"
    },
    {
      "displayText": "Product Elimination - from system"
    }
  ],
  "outcomeItems": [
    {
      "displayText": "API Versioning changes with backwards compatibility"
    },
    {
      "displayText": "Network Mark-In/Mark-Out Servers"
    },
    {
      "displayText": "Phased Rollout, Milestones and Release Candidate"
    },
    {
      "displayText": "Software toggle to Enable/Disable OAuth Server"
    }
  ],
  "slideShow": false,
  "scale": 1.2,
  "scoreCardTheme": {
    "titleColor": "#27005D",
    "initiativeTitleColor": "#27005D",
    "outcomeTitleColor": "#27005D",
    "backgroundColor": "#FF74B1",
    "initiativeBackgroundColor": "#FF90BC",
    "outcomeBackgroundColor": "#FF90BC",
    "initiativeDisplayTextColor": "#27005D",
    "outcomeDisplayTextColor": "#27005D",
    "arrowColor": "#FF90BC"
  }
}
